# fastf1 no es consistente con el campo 'Location': el mismo circuito aparece
# con distinta grafía según el año (Monaco/Monte Carlo, Bahrain/Sakhir,
# Miami/Miami Gardens, Yas Marina/Yas Island, Montreal/Montréal), y para varios
# usa el nombre de la ciudad y no el del circuito (Austin, Barcelona, Budapest,
# Spielberg, Mexico City, São Paulo, Lusail).
#
# Las claves de DATOS_CIRCUITOS son la grafía que fastf1 usa en los años más
# recientes; ALIAS_LOCATION traduce todas las demás a esa. Usar la grafía de
# fastf1 como canónica (en vez de nombres "lindos" tipo COTA o Catalunya) hace
# que los mapas ya cacheados en cache_tracks/ se sigan reusando tal cual.
ALIAS_LOCATION = {
    # variantes del mismo circuito según el año
    "Monte Carlo": "Monaco",
    "Montréal": "Montreal",
    "Miami Gardens": "Miami",
    "Yas Island": "Yas Marina",
    "Abu Dhabi": "Yas Marina",
    "Bahrain": "Sakhir",
    "Singapore": "Marina Bay",
    "Spa": "Spa-Francorchamps",
    "Nürburg": "Nürburgring",
    "Portimao": "Portimão",

    # ciudad en el calendario, nombre del circuito en el uso corriente
    "COTA": "Austin",
    "Catalunya": "Barcelona",
    "Hungaroring": "Budapest",
    "Red Bull Ring": "Spielberg",
    "Hermanos Rodriguez": "Mexico City",
    "Interlagos": "São Paulo",
    "Losail": "Lusail",
    "Paul Ricard": "Le Castellet",
    "Fuji": "Oyama",
    "Buddh": "Uttar Pradesh",
    "Korea": "Yeongam County",

    # 2022: sesión de test de pretemporada en Barcelona, sin circuito propio
    "Spain": "Barcelona",
    # error de datos conocido en el calendario 2026 de FastF1: el GP de Baréin
    # aparece con Location "Kuala Lumpur"
    "Kuala Lumpur": "Sakhir",
}


def normalizar_location(location):
    """Traduce la grafía que vino del calendario a la clave canónica."""
    if not isinstance(location, str):
        return location
    return ALIAS_LOCATION.get(location, location)


DATOS_CIRCUITOS = {
    "Monza": {
        "nombre_completo": "Autodromo Nazionale Monza",
        "circuit_id": "monza",
        "tipo": "Permanente",
        "sentido": "Horario",
        "longitud_km": 5.793,
        "vueltas": 53,
        "distancia_km": 306.720,
        "curvas": 11,
        "record_vuelta": "1:21.046 — Rubens Barrichello (2004)",
        "primer_gp": 1950,
    },
    "Sakhir": {
        "nombre_completo": "Bahrain International Circuit",
        "circuit_id": "bahrain",
        "tipo": "Permanente",
        "sentido": "Horario",
        "longitud_km": 5.412,
        "vueltas": 57,
        "distancia_km": 308.238,
        "curvas": 15,
        "record_vuelta": "1:31.447 — Pedro de la Rosa (2005)",
        "primer_gp": 2004,
    },
    "Jeddah": {
        "nombre_completo": "Jeddah Corniche Circuit",
        "circuit_id": "jeddah",
        "tipo": "Callejero",
        "sentido": "Antihorario",
        "longitud_km": 6.174,
        "vueltas": 50,
        "distancia_km": 308.450,
        "curvas": 27,
        "record_vuelta": "1:30.734 — Lewis Hamilton (2021)",
        "primer_gp": 2021,
    },
    "Melbourne": {
        "nombre_completo": "Albert Park Circuit",
        "circuit_id": "albert_park",
        "tipo": "Semipermanente",
        "sentido": "Horario",
        "longitud_km": 5.278,
        "vueltas": 58,
        "distancia_km": 306.124,
        "curvas": 14,
        "record_vuelta": "1:19.813 — Charles Leclerc (2024)",
        "primer_gp": 1996,
    },
    "Imola": {
        "nombre_completo": "Autodromo Enzo e Dino Ferrari",
        "circuit_id": "imola",
        "tipo": "Permanente",
        "sentido": "Antihorario",
        "longitud_km": 4.909,
        "vueltas": 63,
        "distancia_km": 309.049,
        "curvas": 19,
        "record_vuelta": "1:15.484 — Lewis Hamilton (2020)",
        "primer_gp": 1980,
    },
    "Miami": {
        "nombre_completo": "Miami International Autodrome",
        "circuit_id": "miami",
        "tipo": "Semipermanente",
        "sentido": "Antihorario",
        "longitud_km": 5.412,
        "vueltas": 57,
        "distancia_km": 308.326,
        "curvas": 19,
        "record_vuelta": "1:29.708 — Max Verstappen (2023)",
        "primer_gp": 2022,
    },
    "Barcelona": {
        "nombre_completo": "Circuit de Barcelona-Catalunya",
        "circuit_id": "catalunya",
        "tipo": "Permanente",
        "sentido": "Horario",
        "longitud_km": 4.657,
        "vueltas": 66,
        "distancia_km": 307.236,
        "curvas": 14,
        "record_vuelta": "1:16.330 — Max Verstappen (2023)",
        "primer_gp": 1991,
    },
    "Madrid": {
        "nombre_completo": "Madring",
        "circuit_id": "madring",
        "tipo": "Semipermanente",
        "sentido": "Horario",
        "longitud_km": 5.414,
        "vueltas": 57,
        "distancia_km": 308.399,
        "curvas": 22,
        "record_vuelta": "1:35.587 — George Russell (2026)",
        "primer_gp": 2026,
    },
    "Monaco": {
        "nombre_completo": "Circuit de Monaco",
        "circuit_id": "monaco",
        "tipo": "Callejero",
        "sentido": "Horario",
        "longitud_km": 3.337,
        "vueltas": 78,
        "distancia_km": 260.286,
        "curvas": 19,
        "record_vuelta": "1:12.909 — Lewis Hamilton (2021)",
        "primer_gp": 1950,
    },
    "Montreal": {
        "nombre_completo": "Circuit Gilles-Villeneuve",
        "circuit_id": "villeneuve",
        "tipo": "Semipermanente",
        "sentido": "Horario",
        "longitud_km": 4.361,
        "vueltas": 70,
        "distancia_km": 305.270,
        "curvas": 14,
        "record_vuelta": "1:13.078 — Valtteri Bottas (2019)",
        "primer_gp": 1978,
    },
    "Spielberg": {
        "nombre_completo": "Red Bull Ring",
        "circuit_id": "red_bull_ring",
        "tipo": "Permanente",
        "sentido": "Horario",
        "longitud_km": 4.318,
        "vueltas": 71,
        "distancia_km": 306.452,
        "curvas": 10,
        "record_vuelta": "1:05.619 — Carlos Sainz (2020)",
        "primer_gp": 1970,
    },
    "Silverstone": {
        "nombre_completo": "Silverstone Circuit",
        "circuit_id": "silverstone",
        "tipo": "Permanente",
        "sentido": "Horario",
        "longitud_km": 5.891,
        "vueltas": 52,
        "distancia_km": 306.198,
        "curvas": 18,
        "record_vuelta": "1:27.097 — Max Verstappen (2020)",
        "primer_gp": 1950,
    },
    "Budapest": {
        "nombre_completo": "Hungaroring",
        "circuit_id": "hungaroring",
        "tipo": "Permanente",
        "sentido": "Horario",
        "longitud_km": 4.381,
        "vueltas": 70,
        "distancia_km": 306.630,
        "curvas": 14,
        "record_vuelta": "1:16.627 — Lewis Hamilton (2020)",
        "primer_gp": 1986,
    },
    "Spa-Francorchamps": {
        "nombre_completo": "Circuit de Spa-Francorchamps",
        "circuit_id": "spa",
        "tipo": "Permanente",
        "sentido": "Horario",
        "longitud_km": 7.004,
        "vueltas": 44,
        "distancia_km": 308.052,
        "curvas": 19,
        "record_vuelta": "1:46.286 — Valtteri Bottas (2018)",
        "primer_gp": 1950,
    },
    "Zandvoort": {
        "nombre_completo": "Circuit Zandvoort",
        "circuit_id": "zandvoort",
        "tipo": "Permanente",
        "sentido": "Horario",
        "longitud_km": 4.259,
        "vueltas": 72,
        "distancia_km": 306.587,
        "curvas": 14,
        "record_vuelta": "1:11.097 — Lewis Hamilton (2021)",
        "primer_gp": 1952,
    },
    "Baku": {
        "nombre_completo": "Baku City Circuit",
        "circuit_id": "baku",
        "tipo": "Callejero",
        "sentido": "Antihorario",
        "longitud_km": 6.003,
        "vueltas": 51,
        "distancia_km": 306.049,
        "curvas": 20,
        "record_vuelta": "1:43.009 — Charles Leclerc (2019)",
        "primer_gp": 2016,
    },
    "Marina Bay": {
        "nombre_completo": "Marina Bay Street Circuit",
        "circuit_id": "marina_bay",
        "tipo": "Callejero",
        "sentido": "Antihorario",
        "longitud_km": 4.940,
        "vueltas": 62,
        "distancia_km": 306.143,
        "curvas": 19,
        "record_vuelta": "1:35.867 — Lewis Hamilton (2023)",
        "primer_gp": 2008,
    },
    "Suzuka": {
        "nombre_completo": "Suzuka International Racing Course",
        "circuit_id": "suzuka",
        "tipo": "Permanente",
        "sentido": "En forma de 8",
        "longitud_km": 5.807,
        "vueltas": 53,
        "distancia_km": 307.471,
        "curvas": 18,
        "record_vuelta": "1:30.983 — Lewis Hamilton (2019)",
        "primer_gp": 1987,
    },
    "Shanghai": {
        "nombre_completo": "Shanghai International Circuit",
        "circuit_id": "shanghai",
        "tipo": "Permanente",
        "sentido": "Horario",
        "longitud_km": 5.451,
        "vueltas": 56,
        "distancia_km": 305.066,
        "curvas": 16,
        "record_vuelta": "1:32.238 — Michael Schumacher (2004)",
        "primer_gp": 2004,
    },
    "Austin": {
        "nombre_completo": "Circuit of The Americas",
        "circuit_id": "americas",
        "tipo": "Permanente",
        "sentido": "Antihorario",
        "longitud_km": 5.513,
        "vueltas": 56,
        "distancia_km": 308.405,
        "curvas": 20,
        "record_vuelta": "1:36.169 — Charles Leclerc (2019)",
        "primer_gp": 2012,
    },
    "Mexico City": {
        "nombre_completo": "Autódromo Hermanos Rodríguez",
        "circuit_id": "rodriguez",
        "tipo": "Permanente",
        "sentido": "Horario",
        "longitud_km": 4.304,
        "vueltas": 71,
        "distancia_km": 305.354,
        "curvas": 17,
        "record_vuelta": "1:17.774 — Valtteri Bottas (2021)",
        "primer_gp": 1963,
    },
    "São Paulo": {
        "nombre_completo": "Autódromo José Carlos Pace",
        "circuit_id": "interlagos",
        "tipo": "Permanente",
        "sentido": "Antihorario",
        "longitud_km": 4.309,
        "vueltas": 71,
        "distancia_km": 305.879,
        "curvas": 15,
        "record_vuelta": "1:10.540 — Valtteri Bottas (2018)",
        "primer_gp": 1973,
    },
    "Las Vegas": {
        "nombre_completo": "Las Vegas Strip Circuit",
        "circuit_id": "vegas",
        "tipo": "Callejero",
        "sentido": "Antihorario",
        "longitud_km": 6.201,
        "vueltas": 50,
        "distancia_km": 310.050,
        "curvas": 17,
        "record_vuelta": "1:35.490 — Oscar Piastri (2023)",
        "primer_gp": 2023,
    },
    "Lusail": {
        "nombre_completo": "Lusail International Circuit",
        "circuit_id": "losail",
        "tipo": "Permanente",
        "sentido": "Horario",
        "longitud_km": 5.419,
        "vueltas": 57,
        "distancia_km": 308.611,
        "curvas": 16,
        "record_vuelta": "1:24.319 — Max Verstappen (2023)",
        "primer_gp": 2021,
    },
    "Yas Marina": {
        "nombre_completo": "Yas Marina Circuit",
        "circuit_id": "yas_marina",
        "tipo": "Permanente",
        "sentido": "Antihorario",
        "longitud_km": 5.281,
        "vueltas": 58,
        "distancia_km": 306.183,
        "curvas": 16,
        "record_vuelta": "1:26.103 — Max Verstappen (2021)",
        "primer_gp": 2009,
    },

    # --- Circuitos que ya no están en el calendario ---
    "Le Castellet": {
        "nombre_completo": "Circuit Paul Ricard",
        "circuit_id": "ricard",
        "tipo": "Permanente",
        "sentido": "Horario",
        "longitud_km": 5.842,
        "vueltas": 53,
        "distancia_km": 309.690,
        "curvas": 15,
        "record_vuelta": "1:32.740 — Sebastian Vettel (2019)",
        "primer_gp": 1971,
    },
    "Portimão": {
        "nombre_completo": "Algarve International Circuit",
        "circuit_id": "portimao",
        "tipo": "Permanente",
        "sentido": "Horario",
        "longitud_km": 4.653,
        "vueltas": 66,
        "distancia_km": 306.828,
        "curvas": 15,
        "record_vuelta": "1:18.750 — Lewis Hamilton (2020)",
        "primer_gp": 2020,
    },
    "Sochi": {
        "nombre_completo": "Sochi Autodrom",
        "circuit_id": "sochi",
        "tipo": "Semipermanente",
        "sentido": "Horario",
        "longitud_km": 5.848,
        "vueltas": 53,
        "distancia_km": 309.745,
        "curvas": 18,
        "record_vuelta": "1:35.761 — Lewis Hamilton (2019)",
        "primer_gp": 2014,
    },
    "Istanbul": {
        "nombre_completo": "Istanbul Park",
        "circuit_id": "istanbul",
        "tipo": "Permanente",
        "sentido": "Antihorario",
        "longitud_km": 5.338,
        "vueltas": 58,
        "distancia_km": 309.396,
        "curvas": 14,
        "record_vuelta": "1:24.770 — Juan Pablo Montoya (2005)",
        "primer_gp": 2005,
    },
    "Hockenheim": {
        "nombre_completo": "Hockenheimring",
        "circuit_id": "hockenheimring",
        "tipo": "Permanente",
        "sentido": "Horario",
        "longitud_km": 4.574,
        "vueltas": 67,
        "distancia_km": 306.458,
        "curvas": 17,
        "record_vuelta": "1:13.780 — Kimi Räikkönen (2004)",
        "primer_gp": 1970,
    },
    "Nürburgring": {
        "nombre_completo": "Nürburgring",
        "circuit_id": "nurburgring",
        "tipo": "Permanente",
        "sentido": "Horario",
        "longitud_km": 5.148,
        "vueltas": 60,
        "distancia_km": 308.623,
        "curvas": 15,
        "record_vuelta": "1:27.776 — Max Verstappen (2020)",
        "primer_gp": 1951,
    },
    "Mugello": {
        "nombre_completo": "Autodromo Internazionale del Mugello",
        "circuit_id": "mugello",
        "tipo": "Permanente",
        "sentido": "Horario",
        "longitud_km": 5.245,
        "vueltas": 59,
        "distancia_km": 309.497,
        "curvas": 15,
        "record_vuelta": "1:15.144 — Lewis Hamilton (2020)",
        "primer_gp": 2020,
    },
    "Indianapolis": {
        "nombre_completo": "Indianapolis Motor Speedway (trazado mixto)",
        "circuit_id": "indianapolis",
        "tipo": "Permanente",
        "sentido": "Horario",
        "longitud_km": 4.192,
        "vueltas": 73,
        "distancia_km": 306.016,
        "curvas": 13,
        "record_vuelta": "1:10.399 — Rubens Barrichello (2004)",
        "primer_gp": 2000,
    },
    "Magny Cours": {
        "nombre_completo": "Circuit de Nevers Magny-Cours",
        "circuit_id": "magny_cours",
        "tipo": "Permanente",
        "sentido": "Horario",
        "longitud_km": 4.411,
        "vueltas": 70,
        "distancia_km": 308.586,
        "curvas": 17,
        "record_vuelta": "1:15.377 — Michael Schumacher (2004)",
        "primer_gp": 1991,
    },
    "Oyama": {
        "nombre_completo": "Fuji Speedway",
        "circuit_id": "fuji",
        "tipo": "Permanente",
        "sentido": "Horario",
        "longitud_km": 4.563,
        "vueltas": 67,
        "distancia_km": 305.721,
        "curvas": 16,
        "record_vuelta": "1:18.426 — Felipe Massa (2008)",
        "primer_gp": 1976,
    },
    "Uttar Pradesh": {
        "nombre_completo": "Buddh International Circuit",
        "circuit_id": "buddh",
        "tipo": "Permanente",
        "sentido": "Horario",
        "longitud_km": 5.125,
        "vueltas": 60,
        "distancia_km": 307.249,
        "curvas": 16,
        "record_vuelta": "1:25.599 — Sebastian Vettel (2011)",
        "primer_gp": 2011,
    },
    "Valencia": {
        "nombre_completo": "Valencia Street Circuit",
        "circuit_id": "valencia",
        "tipo": "Callejero",
        "sentido": "Horario",
        "longitud_km": 5.419,
        "vueltas": 57,
        "distancia_km": 308.883,
        "curvas": 25,
        "record_vuelta": "1:38.683 — Timo Glock (2009)",
        "primer_gp": 2008,
    },
    "Yeongam County": {
        "nombre_completo": "Korea International Circuit",
        "circuit_id": "yeongam",
        "tipo": "Semipermanente",
        "sentido": "Antihorario",
        "longitud_km": 5.615,
        "vueltas": 55,
        "distancia_km": 308.630,
        "curvas": 18,
        "record_vuelta": "1:39.605 — Sebastian Vettel (2011)",
        "primer_gp": 2010,
    },
    # Circuitos que sólo se corrieron antes de 2018 (ninguno tiene mapa). Trazado
    # y récord: los de la última vez que la F1 corrió ahí. "California" es Riverside
    # (1960) y Long Beach (1976-83): va Long Beach.
    "Adelaide": {
        "nombre_completo": "Adelaide Street Circuit",
        "circuit_id": "adelaide",
        "tipo": "Callejero",
        "sentido": "Horario",
        "longitud_km": 3.780,
        "vueltas": 81,
        "distancia_km": 306.180,
        "curvas": 16,
        "record_vuelta": "1:15.381 — Damon Hill (1993)",
        "primer_gp": 1985,
    },
    "Anderstorp": {
        "nombre_completo": "Scandinavian Raceway",
        "circuit_id": "anderstorp",
        "tipo": "Permanente",
        "sentido": "—",
        "longitud_km": 4.031,
        "vueltas": 70,
        "distancia_km": 282.170,
        "curvas": 8,
        "record_vuelta": "1:24.836 — Niki Lauda (1978)",
        "primer_gp": 1973,
    },
    "Berlin": {
        "nombre_completo": "AVUS",
        "circuit_id": "avus",
        "tipo": "Semipermanente",
        "sentido": "—",
        "longitud_km": 8.300,
        "vueltas": 60,
        "distancia_km": 498.000,
        "curvas": 4,
        "record_vuelta": "2:04.5 — Tony Brooks (1959)",
        "primer_gp": 1959,
    },
    "Bern": {
        "nombre_completo": "Circuit Bremgarten",
        "circuit_id": "bremgarten",
        "tipo": "Semipermanente",
        "sentido": "—",
        "longitud_km": 7.280,
        "vueltas": 66,
        "distancia_km": 480.480,
        "curvas": 13,
        "record_vuelta": "2:39.7 — Juan Manuel Fangio (1954)",
        "primer_gp": 1950,
    },
    "Brussels": {
        "nombre_completo": "Nivelles-Baulers",
        "circuit_id": "nivelles",
        "tipo": "Permanente",
        "sentido": "—",
        "longitud_km": 3.724,
        "vueltas": 85,
        "distancia_km": 316.540,
        "curvas": 7,
        "record_vuelta": "1:11.310 — Denny Hulme (1974)",
        "primer_gp": 1972,
    },
    "Buenos Aires": {
        "nombre_completo": "Autódromo Oscar y Juan Gálvez",
        "circuit_id": "galvez",
        "tipo": "Permanente",
        "sentido": "—",
        "longitud_km": 4.259,
        "vueltas": 72,
        "distancia_km": 306.648,
        "curvas": 19,
        "record_vuelta": "1:27.981 — Gerhard Berger (1997)",
        "primer_gp": 1953,
    },
    "California": {
        "nombre_completo": "Long Beach Street Circuit",
        "circuit_id": "long_beach",
        "tipo": "Callejero",
        "sentido": "—",
        "longitud_km": 3.275,
        "vueltas": 75,
        "distancia_km": 245.625,
        "curvas": 18,
        "record_vuelta": "1:28.330 — Niki Lauda (1983)",
        "primer_gp": 1976,
    },
    "Casablanca": {
        "nombre_completo": "Circuito de Ain-Diab",
        "circuit_id": "ain-diab",
        "tipo": "Semipermanente",
        "sentido": "—",
        "longitud_km": 7.603,
        "vueltas": 53,
        "distancia_km": 402.959,
        "curvas": 18,
        "record_vuelta": "2:22.5 — Stirling Moss (1958)",
        "primer_gp": 1958,
    },
    "Castle Donington": {
        "nombre_completo": "Donington Park",
        "circuit_id": "donington",
        "tipo": "Permanente",
        "sentido": "Horario",
        "longitud_km": 4.023,
        "vueltas": 76,
        "distancia_km": 305.748,
        "curvas": 12,
        "record_vuelta": "1:18.029 — Ayrton Senna (1993)",
        "primer_gp": 1993,
    },
    "Clermont-Ferrand": {
        "nombre_completo": "Circuit de Charade",
        "circuit_id": "charade",
        "tipo": "Semipermanente",
        "sentido": "—",
        "longitud_km": 8.055,
        "vueltas": 38,
        "distancia_km": 306.090,
        "curvas": 48,
        "record_vuelta": "2:53.9 — Chris Amon (1972)",
        "primer_gp": 1965,
    },
    "Dallas": {
        "nombre_completo": "Fair Park",
        "circuit_id": "dallas",
        "tipo": "Callejero",
        "sentido": "—",
        "longitud_km": 3.901,
        "vueltas": 67,
        "distancia_km": 261.367,
        "curvas": "—",
        "record_vuelta": "1:45.353 — Niki Lauda (1984)",
        "primer_gp": 1984,
    },
    "Detroit": {
        "nombre_completo": "Detroit Street Circuit",
        "circuit_id": "detroit",
        "tipo": "Callejero",
        "sentido": "—",
        "longitud_km": 4.023,
        "vueltas": 63,
        "distancia_km": 253.449,
        "curvas": 22,
        "record_vuelta": "1:40.464 — Ayrton Senna (1987)",
        "primer_gp": 1982,
    },
    "Dijon": {
        "nombre_completo": "Circuit de Dijon-Prenois",
        "circuit_id": "dijon",
        "tipo": "Permanente",
        "sentido": "Horario",
        "longitud_km": 3.801,
        "vueltas": 79,
        "distancia_km": 300.279,
        "curvas": 12,
        "record_vuelta": "1:05.257 — Alain Prost (1984)",
        "primer_gp": 1974,
    },
    "Eastern Cape Province": {
        "nombre_completo": "Prince George Circuit",
        "circuit_id": "george",
        "tipo": "Semipermanente",
        "sentido": "—",
        "longitud_km": 3.920,
        "vueltas": 85,
        "distancia_km": 333.200,
        "curvas": 9,
        "record_vuelta": "1:27.6 — Jim Clark (1965)",
        "primer_gp": 1962,
    },
    "Estoril": {
        "nombre_completo": "Autódromo do Estoril",
        "circuit_id": "estoril",
        "tipo": "Permanente",
        "sentido": "Horario",
        "longitud_km": 4.360,
        "vueltas": 70,
        "distancia_km": 305.200,
        "curvas": 13,
        "record_vuelta": "1:22.446 — David Coulthard (1994)",
        "primer_gp": 1984,
    },
    "Florida": {
        "nombre_completo": "Sebring International Raceway",
        "circuit_id": "sebring",
        "tipo": "Permanente",
        "sentido": "Horario",
        "longitud_km": 8.360,
        "vueltas": 42,
        "distancia_km": 351.120,
        "curvas": 17,
        "record_vuelta": "3:05.0 — Maurice Trintignant (1959)",
        "primer_gp": 1959,
    },
    "Heusden-Zolder": {
        "nombre_completo": "Circuit Zolder",
        "circuit_id": "zolder",
        "tipo": "Permanente",
        "sentido": "—",
        "longitud_km": 4.262,
        "vueltas": 70,
        "distancia_km": 298.340,
        "curvas": 15,
        "record_vuelta": "1:19.294 — René Arnoux (1984)",
        "primer_gp": 1973,
    },
    "Jerez de la Frontera": {
        "nombre_completo": "Circuito de Jerez",
        "circuit_id": "jerez",
        "tipo": "Permanente",
        "sentido": "Horario",
        "longitud_km": 4.428,
        "vueltas": 69,
        "distancia_km": 305.532,
        "curvas": 15,
        "record_vuelta": "1:23.135 — Heinz-Harald Frentzen (1997)",
        "primer_gp": 1986,
    },
    "Kent": {
        "nombre_completo": "Brands Hatch",
        "circuit_id": "brands_hatch",
        "tipo": "Permanente",
        "sentido": "Horario",
        "longitud_km": 4.207,
        "vueltas": 75,
        "distancia_km": 315.525,
        "curvas": 9,
        "record_vuelta": "1:09.593 — Nigel Mansell (1986)",
        "primer_gp": 1964,
    },
    "Le Mans": {
        "nombre_completo": "Circuit Bugatti",
        "circuit_id": "lemans",
        "tipo": "Permanente",
        "sentido": "Horario",
        "longitud_km": 4.430,
        "vueltas": 80,
        "distancia_km": 354.400,
        "curvas": "—",
        "record_vuelta": "1:36.7 — Graham Hill (1967)",
        "primer_gp": 1967,
    },
    "Lisbon": {
        "nombre_completo": "Circuito de Monsanto",
        "circuit_id": "monsanto",
        "tipo": "Callejero",
        "sentido": "—",
        "longitud_km": 5.440,
        "vueltas": 62,
        "distancia_km": 337.280,
        "curvas": "—",
        "record_vuelta": "2:05.07 — Stirling Moss (1959)",
        "primer_gp": 1959,
    },
    "Liverpool": {
        "nombre_completo": "Aintree Motor Racing Circuit",
        "circuit_id": "aintree",
        "tipo": "Permanente",
        "sentido": "—",
        "longitud_km": 4.828,
        "vueltas": 75,
        "distancia_km": 362.100,
        "curvas": 8,
        "record_vuelta": "1:55.0 — Jim Clark (1962)",
        "primer_gp": 1955,
    },
    "Midrand": {
        "nombre_completo": "Kyalami",
        "circuit_id": "kyalami",
        "tipo": "Permanente",
        "sentido": "Horario",
        "longitud_km": 4.261,
        "vueltas": 72,
        "distancia_km": 306.792,
        "curvas": 13,
        "record_vuelta": "1:17.578 — Nigel Mansell (1992)",
        "primer_gp": 1967,
    },
    "Nevada": {
        "nombre_completo": "Caesars Palace",
        "circuit_id": "las_vegas",
        "tipo": "Callejero",
        "sentido": "Antihorario",
        "longitud_km": 3.650,
        "vueltas": 75,
        "distancia_km": 273.750,
        "curvas": "—",
        "record_vuelta": "1:19.639 — Michele Alboreto (1982)",
        "primer_gp": 1981,
    },
    "New York State": {
        "nombre_completo": "Watkins Glen International",
        "circuit_id": "watkins_glen",
        "tipo": "Permanente",
        "sentido": "Horario",
        "longitud_km": 5.435,
        "vueltas": 59,
        "distancia_km": 320.665,
        "curvas": 11,
        "record_vuelta": "1:34.068 — Alan Jones (1980)",
        "primer_gp": 1961,
    },
    "Okayama": {
        "nombre_completo": "TI Circuit Aida",
        "circuit_id": "okayama",
        "tipo": "Permanente",
        "sentido": "Horario",
        "longitud_km": 3.703,
        "vueltas": 83,
        "distancia_km": 307.349,
        "curvas": 13,
        "record_vuelta": "1:14.023 — Michael Schumacher (1994)",
        "primer_gp": 1994,
    },
    "Ontario": {
        "nombre_completo": "Mosport Park",
        "circuit_id": "mosport",
        "tipo": "Permanente",
        "sentido": "Horario",
        "longitud_km": 3.957,
        "vueltas": 80,
        "distancia_km": 316.560,
        "curvas": 10,
        "record_vuelta": "1:13.299 — Mario Andretti (1977)",
        "primer_gp": 1967,
    },
    "Oporto": {
        "nombre_completo": "Circuito da Boavista",
        "circuit_id": "boavista",
        "tipo": "Callejero",
        "sentido": "—",
        "longitud_km": 7.406,
        "vueltas": 55,
        "distancia_km": 407.330,
        "curvas": 19,
        "record_vuelta": "2:27.53 — John Surtees (1960)",
        "primer_gp": 1958,
    },
    "Pescara": {
        "nombre_completo": "Circuito di Pescara",
        "circuit_id": "pescara",
        "tipo": "Semipermanente",
        "sentido": "—",
        "longitud_km": 25.801,
        "vueltas": 18,
        "distancia_km": 464.418,
        "curvas": "—",
        "record_vuelta": "9:44.6 — Stirling Moss (1957)",
        "primer_gp": 1957,
    },
    "Phoenix": {
        "nombre_completo": "Phoenix Street Circuit",
        "circuit_id": "phoenix",
        "tipo": "Callejero",
        "sentido": "—",
        "longitud_km": 3.721,
        "vueltas": 81,
        "distancia_km": 301.401,
        "curvas": 15,
        "record_vuelta": "1:26.758 — Jean Alesi (1991)",
        "primer_gp": 1989,
    },
    "Quebec": {
        "nombre_completo": "Circuit Mont-Tremblant",
        "circuit_id": "tremblant",
        "tipo": "Permanente",
        "sentido": "—",
        "longitud_km": 4.265,
        "vueltas": 90,
        "distancia_km": 383.850,
        "curvas": 15,
        "record_vuelta": "1:32.2 — Clay Regazzoni (1970)",
        "primer_gp": 1968,
    },
    "Reims": {
        "nombre_completo": "Circuit de Reims-Gueux",
        "circuit_id": "reims",
        "tipo": "Semipermanente",
        "sentido": "—",
        "longitud_km": 8.302,
        "vueltas": 48,
        "distancia_km": 398.496,
        "curvas": 7,
        "record_vuelta": "2:11.3 — Lorenzo Bandini (1966)",
        "primer_gp": 1950,
    },
    "Rio de Janeiro": {
        "nombre_completo": "Autódromo de Jacarepaguá",
        "circuit_id": "jacarepagua",
        "tipo": "Permanente",
        "sentido": "Antihorario",
        "longitud_km": 5.031,
        "vueltas": 61,
        "distancia_km": 306.891,
        "curvas": 11,
        "record_vuelta": "1:32.507 — Riccardo Patrese (1989)",
        "primer_gp": 1978,
    },
    "Rouen": {
        "nombre_completo": "Rouen-Les-Essarts",
        "circuit_id": "essarts",
        "tipo": "Semipermanente",
        "sentido": "—",
        "longitud_km": 6.542,
        "vueltas": 60,
        "distancia_km": 392.520,
        "curvas": 12,
        "record_vuelta": "2:11.4 — Jack Brabham (1964)",
        "primer_gp": 1952,
    },
    "Styria": {
        "nombre_completo": "Zeltweg (aeródromo)",
        "circuit_id": "zeltweg",
        "tipo": "Semipermanente",
        "sentido": "—",
        "longitud_km": 3.186,
        "vueltas": 105,
        "distancia_km": 334.530,
        "curvas": 4,
        "record_vuelta": "1:10.56 — Dan Gurney (1964)",
        "primer_gp": 1964,
    },
}


def obtener_datos_circuito(location):
    return DATOS_CIRCUITOS.get(normalizar_location(location))
