# fastf1 no es consistente con el campo 'Location': el mismo circuito aparece
# con distinta grafía según el año (Monaco/Monte Carlo, Bahrain/Sakhir,
# Miami/Miami Gardens, Yas Marina/Yas Island, Montreal/Montréal), y para varios
# usa el nombre de la ciudad y no el del circuito (Austin, Barcelona, Budapest,
# Spielberg, Mexico City, São Paulo, Lusail).
#
# Las claves de DATOS_CIRCUITOS son la grafía que fastf1 usa en los años más
# recientes; ALIAS_LOCATION traduce todas las demás a esa. Usar la grafía de
# fastf1 como canónica (en vez de nombres "lindos" tipo COTA o Catalunya) hace
# que los mapas ya cacheados en cache_tracks/ se sigan reusando tal cual.
ALIAS_LOCATION = {
    # variantes del mismo circuito según el año
    "Monte Carlo": "Monaco",
    "Montréal": "Montreal",
    "Miami Gardens": "Miami",
    "Yas Island": "Yas Marina",
    "Abu Dhabi": "Yas Marina",
    "Bahrain": "Sakhir",
    "Singapore": "Marina Bay",
    "Spa": "Spa-Francorchamps",
    "Nürburg": "Nürburgring",
    "Portimao": "Portimão",

    # ciudad en el calendario, nombre del circuito en el uso corriente
    "COTA": "Austin",
    "Catalunya": "Barcelona",
    "Hungaroring": "Budapest",
    "Red Bull Ring": "Spielberg",
    "Hermanos Rodriguez": "Mexico City",
    "Interlagos": "São Paulo",
    "Losail": "Lusail",
    "Paul Ricard": "Le Castellet",
    "Fuji": "Oyama",
    "Buddh": "Uttar Pradesh",
    "Korea": "Yeongam County",

    # 2022: sesión de test de pretemporada en Barcelona, sin circuito propio
    "Spain": "Barcelona",
    # error de datos conocido en el calendario 2026 de FastF1: el GP de Baréin
    # aparece con Location "Kuala Lumpur"
    "Kuala Lumpur": "Sakhir",
}


def normalizar_location(location):
    """Traduce la grafía que vino del calendario a la clave canónica."""
    if not isinstance(location, str):
        return location
    return ALIAS_LOCATION.get(location, location)


DATOS_CIRCUITOS = {
    "Monza": {
        "nombre_completo": "Autodromo Nazionale Monza",
        "longitud_km": 5.793,
        "vueltas": 53,
        "distancia_km": 306.720,
        "curvas": 11,
        "record_vuelta": "1:21.046 — Rubens Barrichello (2004)",
        "primer_gp": 1950,
    },
    "Sakhir": {
        "nombre_completo": "Bahrain International Circuit",
        "longitud_km": 5.412,
        "vueltas": 57,
        "distancia_km": 308.238,
        "curvas": 15,
        "record_vuelta": "1:31.447 — Pedro de la Rosa (2005)",
        "primer_gp": 2004,
    },
    "Jeddah": {
        "nombre_completo": "Jeddah Corniche Circuit",
        "longitud_km": 6.174,
        "vueltas": 50,
        "distancia_km": 308.450,
        "curvas": 27,
        "record_vuelta": "1:30.734 — Lewis Hamilton (2021)",
        "primer_gp": 2021,
    },
    "Melbourne": {
        "nombre_completo": "Albert Park Circuit",
        "longitud_km": 5.278,
        "vueltas": 58,
        "distancia_km": 306.124,
        "curvas": 14,
        "record_vuelta": "1:19.813 — Charles Leclerc (2024)",
        "primer_gp": 1996,
    },
    "Imola": {
        "nombre_completo": "Autodromo Enzo e Dino Ferrari",
        "longitud_km": 4.909,
        "vueltas": 63,
        "distancia_km": 309.049,
        "curvas": 19,
        "record_vuelta": "1:15.484 — Lewis Hamilton (2020)",
        "primer_gp": 1980,
    },
    "Miami": {
        "nombre_completo": "Miami International Autodrome",
        "longitud_km": 5.412,
        "vueltas": 57,
        "distancia_km": 308.326,
        "curvas": 19,
        "record_vuelta": "1:29.708 — Max Verstappen (2023)",
        "primer_gp": 2022,
    },
    "Barcelona": {
        "nombre_completo": "Circuit de Barcelona-Catalunya",
        "longitud_km": 4.657,
        "vueltas": 66,
        "distancia_km": 307.236,
        "curvas": 14,
        "record_vuelta": "1:16.330 — Max Verstappen (2023)",
        "primer_gp": 1991,
    },
    "Madrid": {
        "nombre_completo": "Madring",
        "longitud_km": 5.414,
        "vueltas": 57,
        "distancia_km": 308.399,
        "curvas": 22,
        "record_vuelta": "1:35.587 — George Russell (2026)",
        "primer_gp": 2026,
    },
    "Monaco": {
        "nombre_completo": "Circuit de Monaco",
        "longitud_km": 3.337,
        "vueltas": 78,
        "distancia_km": 260.286,
        "curvas": 19,
        "record_vuelta": "1:12.909 — Lewis Hamilton (2021)",
        "primer_gp": 1950,
    },
    "Montreal": {
        "nombre_completo": "Circuit Gilles-Villeneuve",
        "longitud_km": 4.361,
        "vueltas": 70,
        "distancia_km": 305.270,
        "curvas": 14,
        "record_vuelta": "1:13.078 — Valtteri Bottas (2019)",
        "primer_gp": 1978,
    },
    "Spielberg": {
        "nombre_completo": "Red Bull Ring",
        "longitud_km": 4.318,
        "vueltas": 71,
        "distancia_km": 306.452,
        "curvas": 10,
        "record_vuelta": "1:05.619 — Carlos Sainz (2020)",
        "primer_gp": 1970,
    },
    "Silverstone": {
        "nombre_completo": "Silverstone Circuit",
        "longitud_km": 5.891,
        "vueltas": 52,
        "distancia_km": 306.198,
        "curvas": 18,
        "record_vuelta": "1:27.097 — Max Verstappen (2020)",
        "primer_gp": 1950,
    },
    "Budapest": {
        "nombre_completo": "Hungaroring",
        "longitud_km": 4.381,
        "vueltas": 70,
        "distancia_km": 306.630,
        "curvas": 14,
        "record_vuelta": "1:16.627 — Lewis Hamilton (2020)",
        "primer_gp": 1986,
    },
    "Spa-Francorchamps": {
        "nombre_completo": "Circuit de Spa-Francorchamps",
        "longitud_km": 7.004,
        "vueltas": 44,
        "distancia_km": 308.052,
        "curvas": 19,
        "record_vuelta": "1:46.286 — Valtteri Bottas (2018)",
        "primer_gp": 1950,
    },
    "Zandvoort": {
        "nombre_completo": "Circuit Zandvoort",
        "longitud_km": 4.259,
        "vueltas": 72,
        "distancia_km": 306.587,
        "curvas": 14,
        "record_vuelta": "1:11.097 — Lewis Hamilton (2021)",
        "primer_gp": 1952,
    },
    "Baku": {
        "nombre_completo": "Baku City Circuit",
        "longitud_km": 6.003,
        "vueltas": 51,
        "distancia_km": 306.049,
        "curvas": 20,
        "record_vuelta": "1:43.009 — Charles Leclerc (2019)",
        "primer_gp": 2016,
    },
    "Marina Bay": {
        "nombre_completo": "Marina Bay Street Circuit",
        "longitud_km": 4.940,
        "vueltas": 62,
        "distancia_km": 306.143,
        "curvas": 19,
        "record_vuelta": "1:35.867 — Lewis Hamilton (2023)",
        "primer_gp": 2008,
    },
    "Suzuka": {
        "nombre_completo": "Suzuka International Racing Course",
        "longitud_km": 5.807,
        "vueltas": 53,
        "distancia_km": 307.471,
        "curvas": 18,
        "record_vuelta": "1:30.983 — Lewis Hamilton (2019)",
        "primer_gp": 1987,
    },
    "Shanghai": {
        "nombre_completo": "Shanghai International Circuit",
        "longitud_km": 5.451,
        "vueltas": 56,
        "distancia_km": 305.066,
        "curvas": 16,
        "record_vuelta": "1:32.238 — Michael Schumacher (2004)",
        "primer_gp": 2004,
    },
    "Austin": {
        "nombre_completo": "Circuit of The Americas",
        "longitud_km": 5.513,
        "vueltas": 56,
        "distancia_km": 308.405,
        "curvas": 20,
        "record_vuelta": "1:36.169 — Charles Leclerc (2019)",
        "primer_gp": 2012,
    },
    "Mexico City": {
        "nombre_completo": "Autódromo Hermanos Rodríguez",
        "longitud_km": 4.304,
        "vueltas": 71,
        "distancia_km": 305.354,
        "curvas": 17,
        "record_vuelta": "1:17.774 — Valtteri Bottas (2021)",
        "primer_gp": 1963,
    },
    "São Paulo": {
        "nombre_completo": "Autódromo José Carlos Pace",
        "longitud_km": 4.309,
        "vueltas": 71,
        "distancia_km": 305.879,
        "curvas": 15,
        "record_vuelta": "1:10.540 — Valtteri Bottas (2018)",
        "primer_gp": 1973,
    },
    "Las Vegas": {
        "nombre_completo": "Las Vegas Strip Circuit",
        "longitud_km": 6.201,
        "vueltas": 50,
        "distancia_km": 310.050,
        "curvas": 17,
        "record_vuelta": "1:35.490 — Oscar Piastri (2023)",
        "primer_gp": 2023,
    },
    "Lusail": {
        "nombre_completo": "Lusail International Circuit",
        "longitud_km": 5.419,
        "vueltas": 57,
        "distancia_km": 308.611,
        "curvas": 16,
        "record_vuelta": "1:24.319 — Max Verstappen (2023)",
        "primer_gp": 2021,
    },
    "Yas Marina": {
        "nombre_completo": "Yas Marina Circuit",
        "longitud_km": 5.281,
        "vueltas": 58,
        "distancia_km": 306.183,
        "curvas": 16,
        "record_vuelta": "1:26.103 — Max Verstappen (2021)",
        "primer_gp": 2009,
    },

    # --- Circuitos que ya no están en el calendario ---
    "Le Castellet": {
        "nombre_completo": "Circuit Paul Ricard",
        "longitud_km": 5.842,
        "vueltas": 53,
        "distancia_km": 309.690,
        "curvas": 15,
        "record_vuelta": "1:32.740 — Sebastian Vettel (2019)",
        "primer_gp": 1971,
    },
    "Portimão": {
        "nombre_completo": "Algarve International Circuit",
        "longitud_km": 4.653,
        "vueltas": 66,
        "distancia_km": 306.828,
        "curvas": 15,
        "record_vuelta": "1:18.750 — Lewis Hamilton (2020)",
        "primer_gp": 2020,
    },
    "Sochi": {
        "nombre_completo": "Sochi Autodrom",
        "longitud_km": 5.848,
        "vueltas": 53,
        "distancia_km": 309.745,
        "curvas": 18,
        "record_vuelta": "1:35.761 — Lewis Hamilton (2019)",
        "primer_gp": 2014,
    },
    "Istanbul": {
        "nombre_completo": "Istanbul Park",
        "longitud_km": 5.338,
        "vueltas": 58,
        "distancia_km": 309.396,
        "curvas": 14,
        "record_vuelta": "1:24.770 — Juan Pablo Montoya (2005)",
        "primer_gp": 2005,
    },
    "Hockenheim": {
        "nombre_completo": "Hockenheimring",
        "longitud_km": 4.574,
        "vueltas": 67,
        "distancia_km": 306.458,
        "curvas": 17,
        "record_vuelta": "1:13.780 — Kimi Räikkönen (2004)",
        "primer_gp": 1970,
    },
    "Nürburgring": {
        "nombre_completo": "Nürburgring",
        "longitud_km": 5.148,
        "vueltas": 60,
        "distancia_km": 308.623,
        "curvas": 15,
        "record_vuelta": "1:27.776 — Max Verstappen (2020)",
        "primer_gp": 1951,
    },
    "Mugello": {
        "nombre_completo": "Autodromo Internazionale del Mugello",
        "longitud_km": 5.245,
        "vueltas": 59,
        "distancia_km": 309.497,
        "curvas": 15,
        "record_vuelta": "1:15.144 — Lewis Hamilton (2020)",
        "primer_gp": 2020,
    },
    "Indianapolis": {
        "nombre_completo": "Indianapolis Motor Speedway (trazado mixto)",
        "longitud_km": 4.192,
        "vueltas": 73,
        "distancia_km": 306.016,
        "curvas": 13,
        "record_vuelta": "1:10.399 — Rubens Barrichello (2004)",
        "primer_gp": 2000,
    },
    "Magny Cours": {
        "nombre_completo": "Circuit de Nevers Magny-Cours",
        "longitud_km": 4.411,
        "vueltas": 70,
        "distancia_km": 308.586,
        "curvas": 17,
        "record_vuelta": "1:15.377 — Michael Schumacher (2004)",
        "primer_gp": 1991,
    },
    "Oyama": {
        "nombre_completo": "Fuji Speedway",
        "longitud_km": 4.563,
        "vueltas": 67,
        "distancia_km": 305.721,
        "curvas": 16,
        "record_vuelta": "1:18.426 — Felipe Massa (2008)",
        "primer_gp": 1976,
    },
    "Uttar Pradesh": {
        "nombre_completo": "Buddh International Circuit",
        "longitud_km": 5.125,
        "vueltas": 60,
        "distancia_km": 307.249,
        "curvas": 16,
        "record_vuelta": "1:25.599 — Sebastian Vettel (2011)",
        "primer_gp": 2011,
    },
    "Valencia": {
        "nombre_completo": "Valencia Street Circuit",
        "longitud_km": 5.419,
        "vueltas": 57,
        "distancia_km": 308.883,
        "curvas": 25,
        "record_vuelta": "1:38.683 — Timo Glock (2009)",
        "primer_gp": 2008,
    },
    "Yeongam County": {
        "nombre_completo": "Korea International Circuit",
        "longitud_km": 5.615,
        "vueltas": 55,
        "distancia_km": 308.630,
        "curvas": 18,
        "record_vuelta": "1:39.605 — Sebastian Vettel (2011)",
        "primer_gp": 2010,
    },
}


def obtener_datos_circuito(location):
    return DATOS_CIRCUITOS.get(normalizar_location(location))
